//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Music.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MUSIC_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_NOTES                       129
#define IDD_PAGE_NOTES                  129
#define IDI_COMPANY                     131
#define IDD_MAIN                        132
#define IDB_STAFF                       133
#define IDD_PAGE_ABOUT                  134
#define IDB_NOTE                        135
#define IDI_NOTE                        136
#define IDD_PAGE_WELCOME                137
#define IDI_NOTE_2                      138
#define IDI_PIANO2                      140
#define IDI_PIANO                       141
#define IDD_PAGE_RHYTHM                 142
#define IDD_PAGE_PITCH                  143
#define IDD_PAGE_SYMBOLS                144
#define IDR_MAIN_MENU                   145
#define IDD_PAGE_PROGRESS               146
#define IDR_RIGHT1                       300
#define IDR_RIGHT2                       301
#define IDR_RIGHT3                       302
#define IDR_RIGHT4                       303
#define IDR_RIGHT5                       304
#define IDR_RIGHT6                       305
#define IDR_RIGHT7                       306
#define IDR_RIGHT8                       307
#define IDR_RIGHT9                       308
#define IDR_RIGHT10                      309
#define IDR_WRONG1                      400
#define IDR_WRONG2                      401
#define IDR_WRONG3                      402
#define IDR_WRONG4                      403
#define IDR_WRONG5                      404
#define IDR_WRONG6                      405
#define IDS_TAB_0                       500
#define IDS_TAB_1                       501
#define IDS_TAB_2                       502
#define IDC_BTN_NOTES                   1000
#define IDC_BTN_HELP                    1001
#define IDC_BTN_NEXT                    1002
#define IDC_BTN_KEYBOARD                1002
#define IDC_PIC_STAFF                   1003
#define IDC_PIC_NOTES                   1004
#define IDC_BTN_CLOSE                   1005
#define IDC_LST_NOTES                   1006
#define IDC_CBO_STAFF                   1008
#define IDC_BTN_START                   1009
#define IDC_BTN_PAUSE                   1010
#define IDC_BTN_STOP                    1011
#define IDC_CHK_LOG                     1012
#define IDC_CBO_LEVEL                   1013
#define IDC_CBO_INPUT                   1014
#define IDC_TBC                         1015
#define IDC_LBL_WELCOME                 1017
#define IDC_BTN_PLAY                    1018
#define IDC_LBL_NOTE                    1019
#define IDC_BTN_PLAY2                   1020
#define IDC_LBL_INSTRUCTIONS            1021
#define IDC_CBO_TEST                    1022
#define IDC_CBO_NAME                    1024
#define ID_OPTIONS                      32771
#define ID_VIEW_OPTIONS                 32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
